_BASE_: maskformer2_R50_bs16_160k.yaml
# SOLVER:
#   IMS_PER_BATCH: 16
#   BASE_LR: 0.0001
#   MAX_ITER: 160000
#   WARMUP_FACTOR: 1.0
#   WARMUP_ITERS: 0
#   WEIGHT_DECAY: 0.05
#   OPTIMIZER: "ADAMW"
#   LR_SCHEDULER_NAME: "WarmupPolyLR"
#   BACKBONE_MULTIPLIER: 0.1
#   CLIP_GRADIENTS:
#     ENABLED: True
#     CLIP_TYPE: "full_model"
#     CLIP_VALUE: 0.01
#     NORM_TYPE: 2.0
#   AMP:
#     ENABLED: True

SOLVER:
  IMS_PER_BATCH: 12
  MAX_ITER: 215000
  # MAX_ITER: 10
  # AMP:
  #   ENABLED: FALSE
